# Generated by Django 5.0.2 on 2024-05-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stats_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='activity_level',
            field=models.CharField(default='moderately_active', max_length=100),
        ),
    ]
